#! /bin/bash

v . -o jarvis -prod
echo -e "\033[32m✔\033[0m JarVis built successfully"

mv jarvis /usr/local/bin/jarvis
echo -e "\033[32m✔\033[0m JarVis installed successfully"

echo ""
echo -e "\033[34m➜\033[0m Launch JarVis and follow its instructions, config file is in \033[34m~/.config/jarvis/config.toml\033[0m"
